/**
 * Parser tests for pi-codex-env-run.
 * Run with: node --test tests/parser.test.mjs
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import os from "node:os";
import fs from "node:fs";
import path from "node:path";

// Pure parser module: zero pi dependencies, works on any Node >= 22.6
// (Node's built-in TypeScript type stripping).
import { parseEnvironmentToml, findEnvironmentsDir, collectActions, addActionToToml, updateActionInToml, removeActionFromToml, validateEnvironmentToml, renderActionBlock } from "../src/parser.ts";

test("parses simple single-line action with setup", () => {
	const env = parseEnvironmentToml(
		`# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "cross-seed"

[setup]
script = "npm install"

[[actions]]
name = "Run"
icon = "run"
command = "npm run dev"
`,
		"environment.toml",
	);
	assert.equal(env.name, "cross-seed");
	assert.equal(env.setup, "npm install");
	assert.equal(env.actions.length, 1);
	assert.deepEqual(env.actions[0], {
		name: "Run",
		icon: "run",
		command: "npm run dev",
		file: "environment.toml",
	});
});

test("parses multiline triple-quoted command with shell comments", () => {
	const env = parseEnvironmentToml(
		`version = 1
name = "web-app"

[setup]
script = ""

[[actions]]
name = "Start app"
icon = "run"
command = '''
cd "\${CODEX_WORKTREE_PATH:-$PWD}"
./scripts/codex-worktree-up.sh
'''
`,
		"environment.toml",
	);
	assert.equal(env.actions.length, 1);
	assert.equal(env.actions[0].name, "Start app");
	assert.equal(
		env.actions[0].command,
		`cd "\${CODEX_WORKTREE_PATH:-$PWD}"
./scripts/codex-worktree-up.sh`,
	);
});

test("parses multiple actions and cleanup", () => {
	const env = parseEnvironmentToml(
		`version = 1
name = "opnform"

[setup]
script = "make setup"

[cleanup]
script = "make teardown"

[[actions]]
name = "Run"
icon = "run"
command = "make run"

[[actions]]
name = "Test"
icon = "test"
command = "make test"
`,
		"environment.toml",
	);
	assert.equal(env.setup, "make setup");
	assert.equal(env.cleanup, "make teardown");
	assert.equal(env.actions.length, 2);
	assert.deepEqual(
		env.actions.map((a) => a.name),
		["Run", "Test"],
	);
});

test("handles trailing comments and escapes", () => {
	const env = parseEnvironmentToml(
		`[[actions]]
name = "Build" # user comment
icon = "build"
command = "echo \\"hi\\" && ls"
`,
		"environment.toml",
	);
	assert.equal(env.actions.length, 1);
	assert.equal(env.actions[0].name, "Build");
	assert.equal(env.actions[0].command, 'echo "hi" && ls');
});

test("ignores non-string values and unknown tables", () => {
	const env = parseEnvironmentToml(
		`version = 1
flag = true
count = 42

[unknown_table]
foo = "bar"

[[other_array]]
x = 1
`,
		"environment.toml",
	);
	assert.equal(env.actions.length, 0);
});

test("findEnvironmentsDir walks up to project root", () => {
	// Build a temp tree: tmp/project/.codex/environments/
	const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "pi-codex-env-run-"));
	const envDir = path.join(tmp, "project", ".codex", "environments");
	fs.mkdirSync(envDir, { recursive: true });
	fs.writeFileSync(path.join(envDir, "environment.toml"), `[[actions]]\nname = "A"\ncommand = "echo a"\n`);

	const deep = path.join(tmp, "project", "src", "deep", "nested");
	fs.mkdirSync(deep, { recursive: true });
	assert.equal(findEnvironmentsDir(deep), envDir);
	assert.equal(findEnvironmentsDir(path.join(tmp, "other")), undefined);

	fs.rmSync(tmp, { recursive: true, force: true });
});

test("collectActions merges multiple toml files, dedupes by name", () => {
	const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "pi-codex-env-run-"));
	const envDir = path.join(tmp, ".codex", "environments");
	fs.mkdirSync(envDir, { recursive: true });
	fs.writeFileSync(
		path.join(envDir, "environment.toml"),
		`[[actions]]\nname = "Run"\ncommand = "npm run dev"\n[[actions]]\nname = "Test"\ncommand = "npm test"\n`,
	);
	fs.writeFileSync(
		path.join(envDir, "extra.toml"),
		`[[actions]]\nname = "Lint"\ncommand = "npm lint"\n[[actions]]\nname = "Test"\ncommand = "npm test-ci"\n`,
	);

	const actions = collectActions(envDir);
	assert.deepEqual(
		actions.map((a) => a.name),
		["Run", "Test", "Lint"], // environment.toml < extra.toml; later "Test" skipped
	);
	assert.equal(actions.find((a) => a.name === "Test")?.command, "npm test");

	fs.rmSync(tmp, { recursive: true, force: true });
});

test("addActionToToml appends a block, preserves existing content", () => {
	const original = `# header comment
version = 1
name = "app"

[[actions]]
name = "Run"
icon = "run"
command = "npm run dev"
`;
	const updated = addActionToToml(original, { name: "Test", icon: "test", command: "npm test" });
	const env = parseEnvironmentToml(updated, "environment.toml");
	assert.equal(env.actions.length, 2);
	assert.deepEqual(
		env.actions.map((a) => a.name),
		["Run", "Test"],
	);
	assert.ok(updated.includes("# header comment"));
	assert.ok(updated.includes('name = "Test"'));
});

test("addActionToToml renders multi-line command with triple quotes", () => {
	const updated = addActionToToml("", { name: "Dev", command: "cd frontend\nbun dev" });
	assert.ok(updated.includes("command = '''"));
	assert.ok(updated.includes("bun dev"));
	const env = parseEnvironmentToml(updated, "environment.toml");
	assert.equal(env.actions[0].command, "cd frontend\nbun dev");
});

test("updateActionInToml replaces only the target block", () => {
	const original = `[[actions]]
name = "Run"
icon = "run"
command = "npm run dev"

[[actions]]
name = "Lint"
command = "npm lint"
`;
	const updated = updateActionInToml(original, "run", { command: "npm run dev --port 3000" });
	assert.ok(updated);
	const env = parseEnvironmentToml(updated, "environment.toml");
	assert.equal(env.actions.length, 2);
	assert.equal(env.actions[0].command, "npm run dev --port 3000");
	assert.equal(env.actions[1].command, "npm lint");
	assert.ok(updated.includes('name = "Run"'));
	assert.ok(!updated.includes("--port 3000") === false); // command updated, name intact
});

test("updateActionInToml returns null for missing name", () => {
	const updated = updateActionInToml("[[actions]]\nname = \"Run\"\ncommand = \"x\"\n", "Missing", { command: "y" });
	assert.equal(updated, null);
});

test("removeActionFromToml deletes only the target block", () => {
	const original = `[[actions]]
name = "Run"
command = "npm run dev"

[[actions]]
name = "Lint"
command = "npm lint"
`;
	const updated = removeActionFromToml(original, "run");
	assert.ok(updated);
	const env = parseEnvironmentToml(updated, "environment.toml");
	assert.equal(env.actions.length, 1);
	assert.equal(env.actions[0].name, "Lint");
	assert.ok(!updated.includes("npm run dev"));
});

test("removeActionFromToml returns null for missing name", () => {
	const updated = removeActionFromToml("[[actions]]\nname = \"Run\"\ncommand = \"x\"\n", "Nope");
	assert.equal(updated, null);
});

test("validateEnvironmentToml reports missing fields, duplicates and unknown icons", () => {
	const toml = `[[actions]]
name = "Ok"
icon = "run"
command = "npm ok"

[[actions]]
command = "no name"

[[actions]]
name = "NoCmd"

[[actions]]
name = "Dup"
command = "a"

[[actions]]
name = "dup"
command = "b"

[[actions]]
name = "BadIcon"
icon = "rocket"
command = "c"
`;
	const issues = validateEnvironmentToml(toml);
	assert.ok(issues.some((i) => i.level === "error" && i.message.includes("missing required field: name")));
	assert.ok(issues.some((i) => i.level === "error" && i.message.includes('"NoCmd" is missing required field: command')));
	assert.ok(issues.some((i) => i.level === "error" && i.message.includes('duplicate action name "dup"')));
	assert.ok(issues.some((i) => i.level === "warning" && i.message.includes('unknown icon "rocket"')));
});

test("renderActionBlock escapes quotes in names", () => {
	const block = renderActionBlock({ name: 'Say "Hi"', command: "echo hi" });
	assert.ok(block.includes('name = "Say \\"Hi\\""'));
});
