/**
 * Parser tests for pi-codex-env-run.
 * Run with: node --test tests/parser.test.mjs
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import os from "node:os";
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";

// Load the parser through jiti with the same aliases pi's extension loader
// uses, so typebox / pi-ai imports resolve exactly like at runtime.
const require = createRequire("/opt/homebrew/lib/node_modules/@earendil-works/pi-coding-agent/dist/core/extensions/loader.js");
const { createJiti } = await import(
	"/opt/homebrew/lib/node_modules/@earendil-works/pi-coding-agent/node_modules/jiti/lib/jiti.mjs",
);
const aliases = {
	"@earendil-works/pi-coding-agent": "/opt/homebrew/lib/node_modules/@earendil-works/pi-coding-agent/index.js",
	"@earendil-works/pi-ai": "/opt/homebrew/lib/node_modules/@earendil-works/pi-coding-agent/node_modules/@earendil-works/pi-ai/dist/compat.js",
	typebox: require.resolve("typebox"),
};
const jiti = createJiti(import.meta.url, { interopDefault: true, alias: aliases });
const { parseEnvironmentToml, findEnvironmentsDir, collectActions } = await jiti.import(
	path.join(import.meta.dirname, "..", "extensions", "codex-env-run.ts"),
);

test("parses simple single-line action with setup", () => {
	const env = parseEnvironmentToml(
		`# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "cross-seed"

[setup]
script = "npm install"

[[actions]]
name = "Run"
icon = "run"
command = "npm run dev"
`,
		"environment.toml",
	);
	assert.equal(env.name, "cross-seed");
	assert.equal(env.setup, "npm install");
	assert.equal(env.actions.length, 1);
	assert.deepEqual(env.actions[0], {
		name: "Run",
		icon: "run",
		command: "npm run dev",
		file: "environment.toml",
	});
});

test("parses multiline triple-quoted command with shell comments", () => {
	const env = parseEnvironmentToml(
		`version = 1
name = "web-app"

[setup]
script = ""

[[actions]]
name = "Start app"
icon = "run"
command = '''
cd "\${CODEX_WORKTREE_PATH:-$PWD}"
./scripts/codex-worktree-up.sh
'''
`,
		"environment.toml",
	);
	assert.equal(env.actions.length, 1);
	assert.equal(env.actions[0].name, "Start app");
	assert.equal(
		env.actions[0].command,
		`cd "\${CODEX_WORKTREE_PATH:-$PWD}"
./scripts/codex-worktree-up.sh`,
	);
});

test("parses multiple actions and cleanup", () => {
	const env = parseEnvironmentToml(
		`version = 1
name = "opnform"

[setup]
script = "make setup"

[cleanup]
script = "make teardown"

[[actions]]
name = "Run"
icon = "run"
command = "make run"

[[actions]]
name = "Test"
icon = "test"
command = "make test"
`,
		"environment.toml",
	);
	assert.equal(env.setup, "make setup");
	assert.equal(env.cleanup, "make teardown");
	assert.equal(env.actions.length, 2);
	assert.deepEqual(
		env.actions.map((a) => a.name),
		["Run", "Test"],
	);
});

test("handles trailing comments and escapes", () => {
	const env = parseEnvironmentToml(
		`[[actions]]
name = "Build" # user comment
icon = "build"
command = "echo \\"hi\\" && ls"
`,
		"environment.toml",
	);
	assert.equal(env.actions.length, 1);
	assert.equal(env.actions[0].name, "Build");
	assert.equal(env.actions[0].command, 'echo "hi" && ls');
});

test("ignores non-string values and unknown tables", () => {
	const env = parseEnvironmentToml(
		`version = 1
flag = true
count = 42

[unknown_table]
foo = "bar"

[[other_array]]
x = 1
`,
		"environment.toml",
	);
	assert.equal(env.actions.length, 0);
});

test("findEnvironmentsDir walks up to project root", () => {
	// Build a temp tree: tmp/project/.codex/environments/
	const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "pi-codex-env-run-"));
	const envDir = path.join(tmp, "project", ".codex", "environments");
	fs.mkdirSync(envDir, { recursive: true });
	fs.writeFileSync(path.join(envDir, "environment.toml"), `[[actions]]\nname = "A"\ncommand = "echo a"\n`);

	const deep = path.join(tmp, "project", "src", "deep", "nested");
	fs.mkdirSync(deep, { recursive: true });
	assert.equal(findEnvironmentsDir(deep), envDir);
	assert.equal(findEnvironmentsDir(path.join(tmp, "other")), undefined);

	fs.rmSync(tmp, { recursive: true, force: true });
});

test("collectActions merges multiple toml files, dedupes by name", () => {
	const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "pi-codex-env-run-"));
	const envDir = path.join(tmp, ".codex", "environments");
	fs.mkdirSync(envDir, { recursive: true });
	fs.writeFileSync(
		path.join(envDir, "environment.toml"),
		`[[actions]]\nname = "Run"\ncommand = "npm run dev"\n[[actions]]\nname = "Test"\ncommand = "npm test"\n`,
	);
	fs.writeFileSync(
		path.join(envDir, "extra.toml"),
		`[[actions]]\nname = "Lint"\ncommand = "npm lint"\n[[actions]]\nname = "Test"\ncommand = "npm test-ci"\n`,
	);

	const actions = collectActions(envDir);
	assert.deepEqual(
		actions.map((a) => a.name),
		["Run", "Test", "Lint"], // environment.toml < extra.toml; later "Test" skipped
	);
	assert.equal(actions.find((a) => a.name === "Test")?.command, "npm test");

	fs.rmSync(tmp, { recursive: true, force: true });
});
